/*global module:false*/
module.exports = function(grunt) {

  var EMBED_CSS = 'src/embed/css/', 
      EMBED_JS = "../embed/js/";

  // Project configuration.
  grunt.initConfig({

    cssmin: {
      css: {
        src: 'src/etc/css/all.css',
        dest: 'src/etc/css/all.min.css'
      }
    },

    concat: {
      jquiz: {
        src: [
          EMBED_CSS + '*.css'
        ],
        dest: 'src/etc/css/all.css'
      }
    },


    requirejs: {
      jquiz : {
        // almond specific contents
        // *insert almond in all your modules
        almond: true,
        // *replace require script calls, with the almond modules
        // in the following files
        dir: 'build/staging',
        replaceRequireScript: [{
          files: ['build/jquiz/index.html'],
          module: 'app'
        }],
        // "normal" require config
        // *create at least a 'main' module
        // thats necessary for using the almond auto insertion
        paths: {
          jquery                       : EMBED_JS + 'jquery/jquery-1.8.2.min.js',
          jquiz                        : EMBED_JS + 'jQuizMe/jQuizMe-2.2.1.min.js'
        },
        modules: [
          {
          name: 'app',
          include: [
            "jquery",
            "jQuizMe"
          ]}
        ],
         appDir: 'src/',
         baseUrl: 'jquiz/',
        skipModuleInsertion: false,
        optimizeAllPluginResources: true,
        findNestedDependencies: true
      }
    },

  clean: {
        embed: "build/staging/embed/"
    },



    /*  automatically generated by grunt init */
    pkg: '<json:package.json>',
    meta: {
      banner: '/*! <%= pkg.title || pkg.name %> - v<%= pkg.version %> - ' +
        '<%= grunt.template.today("yyyy-mm-dd") %>\n' +
        '<%= pkg.homepage ? "* " + pkg.homepage + "\n" : "" %>' +
        '* Copyright (c) <%= grunt.template.today("yyyy") %> <%= pkg.author.name %>;' +
        ' Licensed <%= _.pluck(pkg.licenses, "type").join(", ") %> */'
    },
    jslint: {
      files: ['grunt.js', 'lib/**/*.js', 'test/**/*.js']
    },
    qunit: {
      files: ['test/**/*.html']
    },
    uglify: {
      options: {
        banner: '<%= banner %>'
      },
      dist: {
        src: '<%= concat.dist.dest %>',
        dest: 'dist/<%= pkg.name %>.min.js'
      }
    },
    watch: {
      files: '<config:lint.files>',
      tasks: 'lint qunit'
    },
    jshint: {
      options: {
        curly: true,
        eqeqeq: true,
        immed: true,
        latedef: true,
        newcap: true,
        noarg: true,
        sub: true,
        undef: true,
        boss: true,
        eqnull: true,
        browser: true
      },
      globals: {}
    },
    uglify: {}
  });

  grunt.loadNpmTasks('grunt-contrib-concat');
  grunt.loadNpmTasks('grunt-contrib-uglify');
  grunt.loadNpmTasks('grunt-contrib-nodeunit');
  grunt.loadNpmTasks('grunt-contrib-jshint');
  grunt.loadNpmTasks('grunt-contrib-watch');

  grunt.loadNpmTasks('grunt-contrib-cssmin');
  grunt.loadNpmTasks('grunt-contrib-requirejs');
  grunt.loadNpmTasks('grunt-contrib-clean');
  grunt.loadNpmTasks('grunt-contrib-qunit');
  grunt.loadNpmTasks('grunt-macreload');
  grunt.loadNpmTasks('grunt-jslint');
  // Default task.
  grunt.registerTask('default', 'jslint qunit concat jsmin');

grunt.registerTask('build:jquiz', 'concat:jquiz requirejs:jquiz clean:embed');
};
